<?php
session_start();
require '../db.php';

/*
|--------------------------------------------------------------------------
| Pitogo EduTrack - Staff Scanner History
|--------------------------------------------------------------------------
| Save as:
| staff/scanner-history.php
|--------------------------------------------------------------------------
*/

date_default_timezone_set('Asia/Manila');

if (!isset($_SESSION['user_id'], $_SESSION['role'])) {
    header("Location: ../index.html");
    exit();
}

$currentUserId = (int)$_SESSION['user_id'];
$currentRole = strtolower(trim($_SESSION['role']));

if ($currentRole !== 'staff') {
    header("Location: ../index.html?error=" . urlencode("Unauthorized access."));
    exit();
}

function e($value) {
    return htmlspecialchars((string)($value ?? ''), ENT_QUOTES, 'UTF-8');
}

function tableExists(PDO $pdo, string $table): bool {
    try {
        $stmt = $pdo->prepare("
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = ?
        ");
        $stmt->execute([$table]);
        return (int)$stmt->fetchColumn() > 0;
    } catch (Exception $e) {
        return false;
    }
}

function safeFetchAll(PDO $pdo, string $sql, array $params = []): array {
    try {
        $stmt = $pdo->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (Exception $e) {
        return [];
    }
}

function safeCount(PDO $pdo, string $sql, array $params = []): int {
    try {
        $stmt = $pdo->prepare($sql);
        $stmt->execute($params);
        return (int)$stmt->fetchColumn();
    } catch (Exception $e) {
        return 0;
    }
}

function fullName(array $row): string {
    return trim(($row['first_name'] ?? '') . ' ' . ($row['last_name'] ?? ''));
}

$stmt = $pdo->prepare("SELECT * FROM users WHERE id = ? LIMIT 1");
$stmt->execute([$currentUserId]);
$staff = $stmt->fetch(PDO::FETCH_ASSOC) ?: [];

$staffName = fullName($staff) ?: 'Staff User';

$staffAvatar = !empty($staff['profile_picture'])
    ? '../uploads/profiles/' . $staff['profile_picture']
    : 'https://ui-avatars.com/api/?name=' . urlencode($staffName) . '&background=0056B3&color=fff';

$search = trim($_GET['search'] ?? '');
$dateFrom = trim($_GET['date_from'] ?? '');
$dateTo = trim($_GET['date_to'] ?? '');

$params = [$currentUserId];

$query = "
    SELECT
        a.*,
        s.first_name,
        s.last_name,
        s.id_num,
        s.email
    FROM attendance a
    JOIN users s ON s.id = a.student_id
    WHERE a.scanned_by = ?
";

if ($search !== '') {
    $query .= "
        AND (
            s.first_name LIKE ?
            OR s.last_name LIKE ?
            OR s.id_num LIKE ?
            OR s.email LIKE ?
        )
    ";
    $s = "%{$search}%";
    array_push($params, $s, $s, $s, $s);
}

if ($dateFrom !== '') {
    $query .= " AND a.attendance_date >= ?";
    $params[] = $dateFrom;
}

if ($dateTo !== '') {
    $query .= " AND a.attendance_date <= ?";
    $params[] = $dateTo;
}

$query .= " ORDER BY a.created_at DESC";

$records = tableExists($pdo, 'attendance') ? safeFetchAll($pdo, $query, $params) : [];

$totalMine = tableExists($pdo, 'attendance')
    ? safeCount($pdo, "SELECT COUNT(*) FROM attendance WHERE scanned_by = ?", [$currentUserId])
    : 0;

$totalMineToday = tableExists($pdo, 'attendance')
    ? safeCount($pdo, "SELECT COUNT(*) FROM attendance WHERE scanned_by = ? AND attendance_date = CURDATE()", [$currentUserId])
    : 0;

$filteredTotal = count($records);

if (isset($_GET['export']) && $_GET['export'] === 'true') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename=Pitogo_EduTrack_Staff_Scanner_History_' . date('Y-m-d') . '.csv');

    $output = fopen('php://output', 'w');

    fputcsv($output, ['Pitogo EduTrack Staff Scanner History']);
    fputcsv($output, ['Generated By', $staffName]);
    fputcsv($output, ['Generated On', date('Y-m-d h:i A')]);
    fputcsv($output, []);

    fputcsv($output, [
        'No.',
        'Student Name',
        'LRN',
        'Email',
        'Date',
        'Time In',
        'Status'
    ]);

    $i = 1;
    foreach ($records as $row) {
        fputcsv($output, [
            $i++,
            trim(($row['first_name'] ?? '') . ' ' . ($row['last_name'] ?? '')),
            $row['id_num'] ?? '',
            $row['email'] ?? '',
            $row['attendance_date'] ?? '',
            $row['time_in'] ?? '',
            $row['status'] ?? ''
        ]);
    }

    fclose($output);
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Scanner History | Pitogo EduTrack</title>

<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

<style>
:root {
    --primary-navy:#0B1C3D;
    --primary-blue:#0056B3;
    --bg-main:#F4F7F9;
    --surface-white:#FFFFFF;
    --text-dark:#1E293B;
    --text-muted:#64748B;
    --border-color:#E2E8F0;
    --success:#10B981;
    --warning:#F59E0B;
    --danger:#EF4444;
    --shadow-sm:0 4px 8px rgba(15,23,42,0.04);
    --shadow-md:0 14px 35px rgba(15,23,42,0.08);
}

* {
    margin:0;
    padding:0;
    box-sizing:border-box;
}

body {
    font-family:'Inter',sans-serif;
    background:var(--bg-main);
    color:var(--text-dark);
    display:flex;
    min-height:100vh;
    overflow-x:hidden;
}

h1,h2,h3,h4 {
    font-family:'Montserrat',sans-serif;
}

.sidebar {
    width:82px;
    height:100vh;
    background:var(--surface-white);
    border-right:1px solid var(--border-color);
    position:fixed;
    left:0;
    top:0;
    z-index:100;
    transition:width .35s ease;
    overflow-x:hidden;
    display:flex;
    flex-direction:column;
}

.sidebar:hover {
    width:285px;
    box-shadow:10px 0 30px rgba(15,23,42,0.08);
}

.sidebar-brand {
    padding:24px 17px;
    display:flex;
    align-items:center;
    gap:15px;
    border-bottom:1px solid var(--border-color);
}

.logo-box {
    min-width:48px;
    height:48px;
    border-radius:14px;
    background:#fff;
    border:1px solid var(--border-color);
    overflow:hidden;
    display:flex;
    align-items:center;
    justify-content:center;
}

.logo-box img {
    width:100%;
    height:100%;
    object-fit:contain;
}

.brand-text,
.nav-label,
.nav-item span {
    opacity:0;
    visibility:hidden;
    transition:opacity .2s ease;
}

.sidebar:hover .brand-text,
.sidebar:hover .nav-label,
.sidebar:hover .nav-item span {
    opacity:1;
    visibility:visible;
}

.brand-text h2 {
    font-size:1.05rem;
    color:var(--primary-navy);
    font-weight:800;
}

.brand-text p {
    font-size:.72rem;
    color:var(--primary-blue);
    font-weight:800;
    text-transform:uppercase;
    letter-spacing:.8px;
}

.nav-menu {
    padding:22px 14px;
    display:flex;
    flex-direction:column;
    gap:5px;
    flex:1;
}

.nav-label {
    margin:14px 0 8px 14px;
    font-size:.72rem;
    font-weight:800;
    color:var(--text-muted);
    text-transform:uppercase;
    letter-spacing:1px;
}

.nav-item {
    padding:14px 10px;
    border-radius:13px;
    display:flex;
    align-items:center;
    gap:20px;
    text-decoration:none;
    color:var(--text-muted);
    font-size:.94rem;
    font-weight:750;
    transition:.3s;
}

.nav-item i {
    min-width:30px;
    text-align:center;
    font-size:1.17rem;
}

.nav-item:hover {
    background:var(--bg-main);
    color:var(--primary-blue);
    transform:translateX(5px);
}

.nav-item.active {
    background:rgba(0,86,179,.08);
    color:var(--primary-blue);
}

.logout-link {
    margin-top:auto;
    color:var(--danger);
}

.main-wrapper {
    margin-left:82px;
    flex:1;
    min-width:0;
}

.top-header {
    height:88px;
    background:var(--surface-white);
    border-bottom:1px solid var(--border-color);
    padding:0 38px;
    display:flex;
    align-items:center;
    justify-content:space-between;
    position:sticky;
    top:0;
    z-index:50;
}

.header-title h1 {
    font-size:1.35rem;
    color:var(--primary-navy);
}

.header-title p {
    font-size:.85rem;
    color:var(--text-muted);
    margin-top:4px;
}

.user-profile {
    display:flex;
    align-items:center;
    gap:14px;
}

.user-info {
    text-align:right;
}

.user-info h4 {
    font-size:.9rem;
    color:var(--primary-navy);
}

.user-info p {
    font-size:.75rem;
    color:var(--text-muted);
}

.avatar {
    width:46px;
    height:46px;
    object-fit:cover;
    border-radius:50%;
    border:2px solid var(--primary-blue);
    padding:2px;
}

.content-area {
    padding:38px;
    max-width:1500px;
    margin:0 auto;
}

.hero-card {
    background:
        linear-gradient(135deg, rgba(11,28,61,.96), rgba(0,86,179,.78)),
        url('../school-bg.jpg');
    background-size:cover;
    background-position:center;
    color:white;
    border-radius:24px;
    padding:34px;
    margin-bottom:28px;
    display:flex;
    justify-content:space-between;
    gap:25px;
    align-items:center;
    flex-wrap:wrap;
}

.hero-card h1 {
    font-size:2rem;
    font-weight:800;
    margin-bottom:8px;
}

.hero-card p {
    color:rgba(255,255,255,.86);
    line-height:1.6;
    max-width:850px;
}

.hero-actions {
    display:flex;
    gap:10px;
    flex-wrap:wrap;
}

.btn-white,
.btn-outline {
    padding:12px 16px;
    border-radius:12px;
    text-decoration:none;
    font-weight:900;
    display:inline-flex;
    align-items:center;
    gap:8px;
}

.btn-white {
    background:#fff;
    color:var(--primary-blue);
}

.btn-outline {
    border:1px solid rgba(255,255,255,.3);
    color:#fff;
}

.stats-grid {
    display:grid;
    grid-template-columns:repeat(3, minmax(180px, 1fr));
    gap:18px;
    margin-bottom:24px;
}

.stat-card {
    background:var(--surface-white);
    padding:22px;
    border-radius:18px;
    border:1px solid var(--border-color);
    display:flex;
    align-items:center;
    gap:16px;
    box-shadow:var(--shadow-sm);
}

.stat-icon {
    width:56px;
    height:56px;
    border-radius:15px;
    display:flex;
    align-items:center;
    justify-content:center;
    font-size:1.3rem;
}

.stat-info h3 {
    font-size:1.65rem;
    font-weight:800;
    color:var(--primary-navy);
}

.stat-info p {
    font-size:.78rem;
    color:var(--text-muted);
    font-weight:800;
    text-transform:uppercase;
}

.toolbar-card {
    background:#fff;
    border:1px solid var(--border-color);
    border-radius:18px;
    padding:20px;
    margin-bottom:22px;
    display:flex;
    gap:12px;
    flex-wrap:wrap;
    box-shadow:var(--shadow-sm);
}

.toolbar-card input {
    padding:11px 14px;
    border:1px solid var(--border-color);
    border-radius:10px;
    background:#F8FAFC;
    outline:none;
}

.btn-filter {
    padding:11px 16px;
    background:var(--primary-blue);
    color:#fff;
    border:none;
    border-radius:10px;
    font-weight:900;
    cursor:pointer;
}

.table-container {
    background:#fff;
    border:1px solid var(--border-color);
    border-radius:18px;
    overflow:auto;
    box-shadow:var(--shadow-sm);
}

table {
    width:100%;
    border-collapse:collapse;
    min-width:1000px;
}

th {
    background:#F8FAFC;
    padding:16px 18px;
    font-size:.78rem;
    font-weight:900;
    color:var(--text-muted);
    text-transform:uppercase;
    border-bottom:2px solid var(--border-color);
    text-align:left;
}

td {
    padding:15px 18px;
    border-bottom:1px solid var(--border-color);
    vertical-align:middle;
}

.badge {
    padding:7px 10px;
    border-radius:999px;
    font-size:.72rem;
    font-weight:900;
    background:#DCFCE7;
    color:#166534;
    text-transform:capitalize;
}

.empty-state {
    text-align:center;
    color:var(--text-muted);
    padding:45px;
}

@media(max-width:760px) {
    .sidebar {
        display:none;
    }

    .main-wrapper {
        margin-left:0;
    }

    .top-header {
        padding:0 20px;
    }

    .content-area {
        padding:24px 18px;
    }

    .stats-grid {
        grid-template-columns:1fr;
    }

    .user-info {
        display:none;
    }
}

/* =========================
   CLEAN PORTRAIT PRINT REPORT
========================= */
.print-header,
.print-meta,
.print-signature {
    display:none;
}

@media print {
    * {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
    }

    body {
        background:#fff !important;
        color:#111827 !important;
        display:block !important;
        font-family: Arial, sans-serif !important;
        margin:0 !important;
        padding:0 !important;
    }

    .sidebar,
    .top-header,
    .hero-card,
    .stats-grid,
    .toolbar-card,
    .hero-actions,
    .btn-white,
    .btn-outline,
    .no-print {
        display:none !important;
    }

    .main-wrapper {
        margin-left:0 !important;
        width:100% !important;
    }

    .content-area {
        padding:0 !important;
        margin:0 !important;
        max-width:none !important;
        width:100% !important;
    }

    .print-header {
        display:flex !important;
        align-items:center !important;
        justify-content:center !important;
        gap:16px !important;
        text-align:center !important;
        border-bottom:2px solid #0B1C3D !important;
        padding-bottom:12px !important;
        margin-bottom:12px !important;
    }

    .print-header img {
        width:72px !important;
        height:72px !important;
        object-fit:contain !important;
    }

    .print-header h2 {
        font-size:20px !important;
        font-weight:800 !important;
        margin:0 !important;
        color:#0B1C3D !important;
        letter-spacing:.4px !important;
    }

    .print-header p {
        font-size:11px !important;
        margin:3px 0 !important;
        color:#334155 !important;
    }

    .print-header h3 {
        font-size:13px !important;
        margin-top:6px !important;
        color:#111827 !important;
        text-transform:uppercase !important;
        letter-spacing:.6px !important;
    }

    .print-meta {
        display:grid !important;
        grid-template-columns:1fr 1fr !important;
        gap:8px !important;
        margin-bottom:12px !important;
    }

    .print-meta div {
        border:1px solid #CBD5E1 !important;
        background:#F8FAFC !important;
        padding:8px 10px !important;
    }

    .print-meta span {
        display:block !important;
        font-size:9px !important;
        font-weight:700 !important;
        color:#64748B !important;
        text-transform:uppercase !important;
        margin-bottom:2px !important;
    }

    .print-meta strong {
        display:block !important;
        font-size:11px !important;
        color:#111827 !important;
    }

    .table-container {
        border:none !important;
        border-radius:0 !important;
        box-shadow:none !important;
        overflow:visible !important;
        background:#fff !important;
    }

    table {
        width:100% !important;
        min-width:0 !important;
        border-collapse:collapse !important;
        table-layout:fixed !important;
        font-size:10px !important;
    }

    thead {
        display:table-header-group !important;
    }

    tr {
        page-break-inside:avoid !important;
    }

    th {
        background:#E5E7EB !important;
        color:#111827 !important;
        border:1px solid #94A3B8 !important;
        padding:6px 5px !important;
        font-size:8.5px !important;
        font-weight:800 !important;
        text-transform:uppercase !important;
    }

    td {
        border:1px solid #CBD5E1 !important;
        padding:6px 5px !important;
        vertical-align:top !important;
        word-wrap:break-word !important;
        overflow-wrap:anywhere !important;
        color:#111827 !important;
    }

    th:nth-child(1), td:nth-child(1) {
        width:7% !important;
        text-align:center !important;
    }

    th:nth-child(2), td:nth-child(2) {
        width:24% !important;
    }

    th:nth-child(3), td:nth-child(3) {
        width:16% !important;
    }

    th:nth-child(4), td:nth-child(4) {
        width:24% !important;
    }

    th:nth-child(5), td:nth-child(5) {
        width:12% !important;
    }

    th:nth-child(6), td:nth-child(6) {
        width:10% !important;
    }

    th:nth-child(7), td:nth-child(7) {
        width:7% !important;
    }

    .badge {
        background:transparent !important;
        color:#111827 !important;
        padding:0 !important;
        border-radius:0 !important;
        font-size:9px !important;
        font-weight:700 !important;
    }

    .empty-state {
        padding:18px !important;
        color:#64748B !important;
    }

    .print-signature {
        display:flex !important;
        justify-content:flex-end !important;
        margin-top:30px !important;
        page-break-inside:avoid !important;
    }

    .signature-box {
        width:220px !important;
        text-align:center !important;
        font-size:11px !important;
        color:#111827 !important;
    }

    .signature-line {
        border-top:1px solid #111827 !important;
        margin-top:34px !important;
        padding-top:5px !important;
        font-weight:800 !important;
    }

    @page {
        size: portrait;
        margin:12mm;
    }
}

</style>
</head>

<body>

<aside class="sidebar">
    <div class="sidebar-brand">
        <div class="logo-box">
            <img src="../school-logo.jpg" alt="Pitogo High School Logo" onerror="this.style.display='none'; this.parentElement.innerHTML='<i class=&quot;fa fa-qrcode&quot;></i>';">
        </div>

        <div class="brand-text">
            <h2>Pitogo EduTrack</h2>
            <p>Staff Scanner</p>
        </div>
    </div>

    <nav class="nav-menu">
        <div class="nav-label">Scanner</div>

        <a href="qr-scanner.php" class="nav-item">
            <i class="fa fa-qrcode"></i>
            <span>QR Scanner</span>
        </a>

        <a href="scanner-history.php" class="nav-item active">
            <i class="fa fa-clock-rotate-left"></i>
            <span>Scanner History</span>
        </a>

        <div class="nav-label">Account</div>

        <a href="../logout.php" class="nav-item logout-link">
            <i class="fa fa-right-from-bracket"></i>
            <span>Logout</span>
        </a>
    </nav>
</aside>

<main class="main-wrapper">

<header class="top-header">
    <div class="header-title">
        <h1>Scanner History</h1>
        <p>Staff Access • Pitogo EduTrack</p>
    </div>

    <div class="user-profile">
        <div class="user-info">
            <h4><?= e($staffName) ?></h4>
            <p>Entrance Staff</p>
        </div>

        <img src="<?= e($staffAvatar) ?>" class="avatar" alt="Staff Profile">
    </div>
</header>

<section class="content-area">

    <section class="hero-card">
        <div>
            <h1>Your QR Scanner History</h1>
            <p>View and export your attendance scanning records.</p>
        </div>

        <div class="hero-actions">
            <a href="qr-scanner.php" class="btn-white">
                <i class="fa fa-qrcode"></i>
                Open Scanner
            </a>

            <a href="?<?= e(http_build_query(array_merge($_GET, ['export' => 'true']))) ?>" class="btn-outline">
                <i class="fa fa-file-csv"></i>
                Export CSV
            </a>

            <button type="button" onclick="window.print()" class="btn-outline" style="border:none; cursor:pointer;">
                <i class="fa fa-print"></i>
                Print Document
            </button>
        </div>
    </section>

    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-icon" style="background:rgba(0,86,179,.1); color:var(--primary-blue);">
                <i class="fa fa-qrcode"></i>
            </div>
            <div class="stat-info">
                <h3><?= number_format($totalMine) ?></h3>
                <p>Total Scans</p>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon" style="background:rgba(16,185,129,.1); color:var(--success);">
                <i class="fa fa-calendar-day"></i>
            </div>
            <div class="stat-info">
                <h3><?= number_format($totalMineToday) ?></h3>
                <p>Today</p>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon" style="background:rgba(245,158,11,.1); color:var(--warning);">
                <i class="fa fa-filter"></i>
            </div>
            <div class="stat-info">
                <h3><?= number_format($filteredTotal) ?></h3>
                <p>Filtered</p>
            </div>
        </div>
    </div>

    <form method="GET" class="toolbar-card">
        <input type="text" name="search" placeholder="Search student name, LRN, email..." value="<?= e($search) ?>">
        <input type="date" name="date_from" value="<?= e($dateFrom) ?>">
        <input type="date" name="date_to" value="<?= e($dateTo) ?>">

        <button type="submit" class="btn-filter">
            <i class="fa fa-filter"></i>
            Filter
        </button>
    </form>


    <div class="print-header">
        <img src="../school-logo.jpg" alt="Pitogo High School Logo">
        <div>
            <h2>PITOGO HIGH SCHOOL</h2>
            <p>Pitogo EduTrack Management System</p>
            <p>Luzon St, Pitogo, Taguig, 1630 Metro Manila, Philippines</p>
            <h3>Staff QR Scanner Attendance Report</h3>
        </div>
    </div>

    <div class="print-meta">
        <div>
            <span>Generated By</span>
            <strong><?= e($staffName) ?></strong>
        </div>

        <div>
            <span>Date Generated</span>
            <strong><?= e(date('F d, Y h:i A')) ?></strong>
        </div>

        <div>
            <span>Date Range</span>
            <strong><?= e($dateFrom !== '' ? $dateFrom : 'All') ?> to <?= e($dateTo !== '' ? $dateTo : 'All') ?></strong>
        </div>

        <div>
            <span>Filtered Records</span>
            <strong><?= e(number_format($filteredTotal)) ?> record(s)</strong>
        </div>
    </div>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Student</th>
                    <th>LRN</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Time In</th>
                    <th>Status</th>
                </tr>
            </thead>

            <tbody>
                <?php if (!$records): ?>
                    <tr>
                        <td colspan="7">
                            <div class="empty-state">
                                <i class="fa fa-folder-open" style="font-size:2rem; margin-bottom:10px;"></i>
                                <br>
                                No scanner history found.
                            </div>
                        </td>
                    </tr>
                <?php else: ?>
                    <?php $i = 1; foreach ($records as $row): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><strong><?= e(trim(($row['first_name'] ?? '') . ' ' . ($row['last_name'] ?? ''))) ?></strong></td>
                            <td><?= e($row['id_num'] ?? 'N/A') ?></td>
                            <td><?= e($row['email'] ?? 'N/A') ?></td>
                            <td><?= !empty($row['attendance_date']) ? e(date('M d, Y', strtotime($row['attendance_date']))) : 'N/A' ?></td>
                            <td><?= !empty($row['time_in']) ? e(date('h:i A', strtotime($row['time_in']))) : 'N/A' ?></td>
                            <td><span class="badge"><?= e($row['status'] ?? 'present') ?></span></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>


<div class="print-signature">
    <div class="signature-box">
        <div class="signature-line"><?= e($staffName) ?></div>
        <div>Entrance Staff / QR Scanner Personnel</div>
    </div>
</div>

</section>

</main>

</body>
</html>
